version: "3"

services:
  redisdb:
      image: redis
      restart: always
      environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_HOST: ${REDIS_HOST}
      networks:
        - redisnetwork

  database:
    image: postgres
    restart: always
    ports:
      - ${DATABASE_API_GATEWAY_HOST}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - dbnetwork

  server:
    image: api-gateway
    build: .
    restart: always
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - database
      - redisdb
    networks:
      - dbnetwork
      - redisnetwork

networks:
  dbnetwork: {}
  redisnetwork: {}